"""initial schema

Revision ID: 59b2f97d52ba
Revises: 
Create Date: 2026-08-29 14:47:32.797154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b2f97d52ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_sharp', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_bookmakers_key')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', name='uq_leagues_provider_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_teams_name')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_fixture_id', sa.String(length=128), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_fixture_id', name='uq_fixtures_provider_fixture_id')
    )
    op.create_index('ix_fixtures_kickoff_at', 'fixtures', ['kickoff_at'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lambda_home', sa.Float(), nullable=False),
    sa.Column('lambda_away', sa.Float(), nullable=False),
    sa.Column('lambda_total', sa.Float(), nullable=False),
    sa.Column('market_baseline_used', sa.Boolean(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=32), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_snapshots_lookup', 'odds_snapshots', ['fixture_id', 'bookmaker_id', 'market_code', 'selection', 'line', 'source_timestamp'], unique=False)
    op.create_table('market_predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_run_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=32), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('bookmaker_odds', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_codes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_predictions')
    op.drop_index('ix_odds_snapshots_lookup', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('model_runs')
    op.drop_index('ix_fixtures_kickoff_at', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
